apiVersion: apps/v1
kind: Deployment
metadata:
  name: peercalls
spec:
  progressDeadlineSeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: peercalls
  template:
    metadata:
      labels:
        app.kubernetes.io/name: peercalls
    spec:
      volumes:
      - name: peercalls-config
        configMapRef:
        - name: peercalls-config
      containers:
      - name: peercalls
        image: peercalls/peercalls
        imagePullPolicy: IfNotPresent
        command: ["-c", "/etc/peercalls/config.yaml"]
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /probes/live
            port: http
          timeoutSeconds: 5
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /probe/ready
            port: http
          timeoutSeconds: 5
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: peercalls-config
          mountPath: /etc/peercalls/config.yaml
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - "10"
      serviceAccountName: peercalls
      securityContext:
        fsGroup: 1000
