# This workflow will do a clean install of node and go dependencies, and run the CI scripts

name: Node.js CI

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: []

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["12.x"]
        go-version: ["1.14"]
        arch:
          - "GOOS=linux GOARCH=amd64 BINARY=peer-calls"
          - "GOOS=linux GOARCH=arm BINARY=peer-calls"
          - "GOOS=darwin GOARCH=amd64 BINARY=peer-calls"
          - "GOOS=windows GOARCH=amd64 BINARY=peer-calls.exe"
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run ci
    - name: Use Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2.0.3
      with:
        go-version: ${{ matrix.go-version }}
    - run: go get -u github.com/gobuffalo/packr/packr
    - run: go test ./... -race -coverageprofile=coverage.out
    - run: go tool cover -func=coverage.out
    - name: Build ${{ matrix.arch }}
      run: export ${{matrix.arch}}
    - run: mkdir -p build/$GOOS/$GOARCH
    - run: packr build -ldflags "-X main.gitDescribe=$(git describe --always --tags)" -o build/$GOOS/$GOARCH/$BINARY main.go
    - name: Release ${{ matrix.arch }}
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      # if: startsWith(github.ref, 'refs/tags/v')
      if: ${{ github.ref == 'github-actions' }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Peer Calls v4 ${{ github.ref }}
        # body: |
        #   Changes in this Release
        #   - First Change
        #   - Second Change
        draft: false
        prerelease: true
